### ISSUE TITLE
Request for Source Dataset of FewGLUE_64_labeled

### ISSUE THREAD

**Issue by jiangdaolime** [claws-lab/few-shot-adversarial-robustness#1]
FewGLUE_64_labeled is no longer available for download. Please ask if it would be possible to re-supply a link where the download can be made available. Any data provided will be used for research purposes only.

**Comment by gaurav22verma** [comment]
Hi! Thanks for your interest. The FewNLU benchmark (leaderboard + dataset) is maintainted by the authors of [this work](https://fewnlu.github.io/); their contact details are included. The original download [link](https://cloud.tsinghua.edu.cn/f/03b187bf3fff4a5fb1d1/?dl=1) seems to be down. Also, worth clarifying that we use the scripts (which are still available [here](https://github.com/THUDM/FewNLU?tab=readme-ov-file#customizing-your-own-tasks)) to construct the few-shot training and evaluation datasets for our experiments on the AdvGLUE tasks. The AdvGLUE tasks have some GLUE tasks that are not covered in FewNLU. You could consider doing the same!

**Comment by gaurav22verma** [comment]
original download link is down; please contact authors of the source dataset
